server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/jongmin/native-file-repo
        git:
          uri: https://github.com/chungjm/spring-cloud-config.git
#          username: [username]
#          password: [password]
#          uri: file:///Users/jongminchung/Desktop/jongmin/project/spring-cloud-config
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
